### ISSUE TITLE
create users

### ISSUE THREAD

**Issue by meganrm** [townhallproject/townhall-SMS-alerts#40]

**Comment by hanhthaoluu** [comment]
created the user constructor

**Comment by DarDavis** [comment]
Finished that up! Me and James did some pair programming, when a user sends 'subscribe <zip>' their info is stored in sms-users @jrzollin 💯💯

**Comment by DarDavis** [comment]
I worked, now it doesn't. most up to date code is in the feature/saveUser branch. I even rolled back to the working branch but now it doesn't update firebase 👎  sad.

**Comment by meganrm** [comment]
Nice job
