### ISSUE TITLE
Send test vol recruitment text

### ISSUE THREAD

**Issue by nathanmwilliams** [townhallproject/townhall-SMS-alerts#94]
To 250 text subscribers. Ideally at 6pm ET or thereabouts.

Forward replies to Nathan (206.300.2296) in a way that lets Nathan reply in the same text chain.

COPY:

Hi [name]! This is Nathan with Town Hall Project. Our mission to hold our elected leaders accountable to the people they work for (the people!) is *only* possible with our volunteers. 

We're less than a month away from a 5-week Congressional recess --when most of the town halls for the entire year are held, and we need YOUR help! 

Can you volunteer just 1 hour / week to help us make sure Americans are informed of crucial opportunities to Show Up and Speak Out. 

If you're interested, please contact us via this short form: bit.ly/2J3kQMD. 

With your help, we can take back our democracy and make this the country we know it can be.

[+ the standard opt out text]

**Comment by meganrm** [comment]
just fyi, for some phones this message will get divided into two or three since it's so long

**Comment by nathanmwilliams** [comment]
Hmm. What's our Max allowable characters for those, 140?

Also, you have any idea how many phones in use today still have that restriction?

**Comment by meganrm** [comment]
I dunno. Here is the info from Twilio: When you send a SMS message over 160 characters the message will be split. Large messages are segmented into 153 character segements and sent individually then rebuilt by the recipients device. For example, a 161 character message will be sent as two messages, one with 153 characters and the second with 8 characters.

**Comment by nathanmwilliams** [comment]
Gotcha. Let me see if I can massage the copy into fewer texts. You pretty much good otherwise?

**Comment by nathanmwilliams** [comment]
Okay, broke this down into three messages under 160 characters. Is this the way to do it, or would it just break up the text mid-sentence at 160?

---
**1**
Hi! Nathan here with Town Hall Project. 

We're weeks away from a 5-week Congressional recess --when hundreds of town halls are held, and we need YOUR help!

**2**
Can you volunteer just 1 hour / week from your own home to help us make sure Americans are informed of crucial opportunities to Show Up and Speak Out.

**3**
There’s no easier way to play a powerful part in holding our elected officials accountable. To learn more, please reply back with YES.
